name = "polygon-agentic-docs"
compatibility_date = "2024-07-04"
workers_dev = false
preview_urls = false
send_metrics = false
placement = { mode = "smart" }

[assets]
directory = "./out"

[env.staging]
routes = [
  { pattern = "agentic-docs.staging.polygon.technology", custom_domain = true }
]

[env.production]
# Update the pattern below once the production domain is assigned.
routes = [
      { pattern = "agentic-docs.polygon.technology", custom_domain = true }
]
